# Modules

obj-m += cpufreq_conservative.o cpufreq_interactive.o cpufreq_powersave.o
obj-m += cpufreq_stats.o
obj-m += cpufreq_smartass.o cpufreq_boosted.o

sio_iosched-objs = sio-iosched.o
obj-m += sio_iosched.o

