#!/bin/bash

# Require a Motorola Android Repository
# 1. put modules folders in /drivers/misc/
# 2. edit drivers/misc/Makefile and add :
#     obj-m += symsearch/
#     obj-m += overclock/
#     obj-m += mmcfix/
#     obj-m += usbled/
# 3. edit drivers/misc/Kconfig and add :
#     source "drivers/misc/symsearch/Kconfig"
#     source "drivers/misc/overclock/Kconfig"
#     source "drivers/misc/mmcfix/Kconfig"
#     source "drivers/misc/usbled/Kconfig"

#output :
# out/target/product/generic/obj/PARTITIONS/kernel_intermediates/build/.config  (to clean, rm -r)
# out/target/product/generic/obj/PARTITIONS/kernel_intermediates/build/drivers/misc/

make MOTO_PREBUILT_DIR= kernel $*

OUTPUT=out/target/product/generic/obj/PARTITIONS/kernel_intermediates/build/drivers/misc
OUT_DIR=./

cp $OUTPUT/symsearch/symsearch.ko $OUT_DIR
cp $OUTPUT/overclock/*.ko $OUT_DIR
cp $OUTPUT/mmcfix/mmcfix.ko $OUT_DIR
cp $OUTPUT/usbled/usbled.ko $OUT_DIR

