#!/sbin/sh

# Motorola Defy CWM3 Recovery Only..
# 2011/05/15 replace tune2fs

echo "****************************************"
echo "hijack $0.. original file: $0.bin"
echo "****************************************"

for arg in $*; do
  if [ $arg == "/dev/block/mmcblk1p21" ] || [ $arg == "/dev/block/system" ]; then
    $0.bin -C 1 $arg
    exit $?
  elif [ $arg == "/dev/block/mmcblk1p25" ] || [ $arg == "/dev/block/userdata" ]; then
    $0.bin -C 1 $arg
    exit $?
  fi
done

$0.bin $*
exit $?
