#!/system/bin/sh
#
# load module to fix fast sdcards

# Module location
MODULE="/system/lib/modules/mmcfix.ko"

# Property to disable the module
LOAD_MMCFIX=`getprop persist.sys.mmcfix.disable`

if [ "$LOAD_MMCFIX" != "1" ]; then
    modprobe mmcfix
fi

