#!/system/bin/sh
#
# allow use of white led when usb is plugged

# Module location
MODULE="/system/lib/modules/usbled.ko"

# Property to disable the module
LOAD_MODULE=`getprop persist.sys.usbled.disable`

if [ "$LOAD_MODULE" != "1" ]; then
    insmod $MODULE
fi

