#!/system/bin/sh
#
# load module to fix old devtree gpio names

# Module location
MODULE="/system/lib/modules/gpiofix.ko"

# Property to disable the module
LOAD_MODULE=`getprop persist.sys.gpiofix.disable`

if [ "$LOAD_MODULE" != "1" ]; then
    insmod $MODULE
fi

