#!/system/bin/sh
#
# load multitouch module

# Module location
MODULE="/system/lib/modules/defy_more.ko"

# Module address (0xc00939c4 for kernel 179)
ADDR=`grep "T kallsyms_lookup_name" /proc/kallsyms | cut -d " " -f 1`

# Load the module into address
insmod $MODULE kallsyms_lookup_name_addr=0x$ADDR