#!/system/bin/sh
#
# load module to allow button backlight level changes

# Module location
MODULE="/system/lib/modules/backlight.ko"

# Property to disable the module
LOAD_MODULE=`getprop persist.sys.backlight.disable`

if [ "$LOAD_MODULE" != "1" ]; then
    insmod $MODULE brightness=4 log_enable=0 hook_enable=0
fi

