#!/system/xbin/ash

# copy dnsmasq.conf to data wifi if it doesnt exists...
if [ ! -f /data/misc/wifi/dns.conf ]; then

  cp /system/etc/wifi/dnsmasq.conf /data/misc/wifi/dns.conf

  chown wifi.wifi /data/misc/wifi/dns.conf
  chmod 666 /data/misc/wifi/dns.conf

fi

