#!/system/bin/sh
#
# load module to provide Kineto network interface

# Module location
MODULE="/system/lib/modules/kineto_gan.ko"

# Property to disable the module
LOAD_MODULE=`getprop persist.sys.kineto.enable`

if [ "$LOAD_MODULE" = "1" ]; then
    /system/xbin/insmod $MODULE
fi

