#!/system/bin/sh
#
# load multitouch module

# Module location
MODULE="/system/lib/modules/multitouch.ko"

# Max number of fingers
MAX_TOUCH=`getprop persist.sys.multitouch`
if [ -z "$MAX_TOUCH" ]; then
    MAX_TOUCH=2
fi

# Load the module
insmod $MODULE touch_num=$MAX_TOUCH
